import { useState, useRef, useEffect } from 'react';
import { motion, useInView, Variants } from 'framer-motion';
import { Scale, Mail, Phone } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '@/contexts/AuthContext';
import ProfileMenu from '@/components/ui/profile-menu';

const luxuryEasing: [number, number, number, number] = [0.22, 1, 0.36, 1];

const fadeInUp: Variants = {
  hidden: { opacity: 0, y: 80 },
  visible: { 
    opacity: 1, 
    y: 0,
    transition: { duration: 1.2, ease: luxuryEasing }
  }
};

const staggerContainer: Variants = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: {
      staggerChildren: 0.3,
      delayChildren: 0.2
    }
  }
};

const textReveal: Variants = {
  hidden: { y: "120%", opacity: 0 },
  visible: { 
    y: 0, 
    opacity: 1,
    transition: { duration: 1.4, ease: luxuryEasing }
  }
};

const AnimatedSection = ({ 
  children, 
  className = '', 
  dark = true,
  id = ''
}: { 
  children: React.ReactNode; 
  className?: string; 
  dark?: boolean;
  id?: string;
}) => {
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true, margin: "-100px" });
  
  return (
    <motion.section
      id={id}
      ref={ref}
      className={`${dark ? 'bg-[#0A0A0A] text-[#F5F5F3]' : 'bg-[#F5F5F3] text-[#0A0A0A]'} ${className}`}
      initial="hidden"
      animate={isInView ? "visible" : "hidden"}
      variants={staggerContainer}
    >
      {children}
    </motion.section>
  );
};

const TermsAndConditions = () => {
  const navigate = useNavigate();
  const { user } = useAuth();
  const [isNavVisible, setIsNavVisible] = useState(true);
  const [lastScrollY, setLastScrollY] = useState(0);

  // Handle scroll to show/hide navbar
  useEffect(() => {
    const handleScroll = () => {
      const currentScrollY = window.scrollY;
      
      if (currentScrollY < 50 || currentScrollY < lastScrollY) {
        setIsNavVisible(true);
      } else if (currentScrollY > lastScrollY && currentScrollY > 50) {
        setIsNavVisible(false);
      }
      
      setLastScrollY(currentScrollY);
    };

    window.addEventListener('scroll', handleScroll, { passive: true });
    return () => window.removeEventListener('scroll', handleScroll);
  }, [lastScrollY]);

  const sections = [
    {
      number: 1,
      title: "Standard of Agreement",
      content: "By accessing or utilizing the digital properties and advisory services provided by Cleub Automation, you confirm your unconditional acceptance of these Terms and Conditions. This document establishes the formal Standard of Engagement between you and Cleub Automation. Should you dissent from any term, you must immediately cease all use of our services."
    },
    {
      number: 2,
      title: "The Scope of Cleub Expertise",
      subtitle: "(Services Description)",
      items: [
        { label: "Architectural Planning", desc: "Exclusive digital platforms for high-level project conceptualization and preliminary cost scoping." },
        { label: "System Integrity", desc: "Professional design, supply, and installation of advanced wired, wireless, and hybrid automation ecosystems." },
        { label: "A/V Excellence", desc: "Implementation of cinema-grade home theaters and professional audio-visual studios." },
        { label: "Strategic Advisory", desc: "Expert consultation and unbiased guidance on technology selection and integration." }
      ]
    },
    {
      number: 3,
      title: "Client Accountability and Portal Access",
      content: "Access to our restricted planning and project portals requires the creation of a private account. You assume full, exclusive responsibility for the absolute confidentiality of your private credentials, all activities initiated under your unique account identifier, and the provision of accurate, complete, and current information critical to system design. Cleub Automation reserves the right to immediately suspend or permanently terminate access for any violation of these terms, protecting the integrity of our platform."
    },
    {
      number: 4,
      title: "Preliminary Scoping and Formal Quotation",
      subtitle: "(Cost Estimates)",
      content: "The cost estimates generated by our proprietary planning tools are preliminary and illustrative only. Final Project Valuation is subject to mandatory site audits, market dynamics in premium component pricing, and scope refinement. Only a formal, detailed written proposal and service contract signed by an authorized Cleub principal constitutes a binding agreement for cost and deliverables."
    },
    {
      number: 5,
      title: "Intellectual Property: The Cleub Standard",
      content: "All methodologies, proprietary software code, system schematics, architectural designs, graphics, and textual content accessible through our services are the exclusive intellectual property of Cleub Automation. You are expressly prohibited from unauthorized reproduction, modification, distribution, reverse engineering attempts, or unapproved use of our trade names and brand identifiers."
    },
    {
      number: 6,
      title: "Engagement and Contractual Certainty",
      items: [
        { label: "Inquiry Response", desc: "We commit to an initial response to consultation requests within one (1) business day." },
        { label: "Formal Agreements", desc: "Detailed proposals will be provided via a separate, definitive Service Agreement." },
        { label: "No Obligation", desc: "The client is under no contractual obligation to proceed until the formal Service Agreement has been duly executed by both parties." }
      ]
    },
    {
      number: 7,
      title: "Limitation of Liability and Non-Reliance",
      content: "To the absolute fullest extent permissible by law, Cleub Automation expressly disclaims liability for non-material damages, reliance risks on preliminary estimates, and external factors outside our direct control. Our liability is strictly limited to the direct fees paid for the specific service under dispute."
    },
    {
      number: 8,
      title: "Warranties and Disclaimers",
      content: "Our services are provided on an 'as is' basis. While Cleub Automation strives for engineering perfection, we do not warrant uninterrupted operation or absolute compatibility with all external third-party devices. All supplied equipment and installed systems are subject to the original manufacturer's warranty."
    },
    {
      number: 9,
      title: "Privacy and Security Mandate",
      content: "Your use of our services is inextricably governed by our Privacy Policy: The Assurance of Discretion. We adhere to stringent data protection standards, recognizing the highly sensitive nature of the information related to your personal estate and lifestyle."
    },
    {
      number: 10,
      title: "Governance and Dispute Resolution",
      content: "These Terms and Conditions are governed by the laws of India. Any disputes shall be subject to direct negotiation, formal mediation, binding arbitration in accordance with Indian arbitration rules, and exclusive jurisdiction of the Courts located in Delhi, India."
    }
  ];

  return (
    <div className="min-h-screen bg-[#0A0A0A] font-sans">
      
      {/* ============================================ */}
      {/* SMART NAVIGATION - HIDES ON SCROLL */}
      {/* ============================================ */}
      <motion.nav 
        className="fixed top-0 left-0 right-0 z-50 mix-blend-difference"
        initial={{ y: -100 }}
        animate={{ 
          opacity: isNavVisible ? 1 : 0,
          y: isNavVisible ? 0 : -100,
          pointerEvents: isNavVisible ? 'auto' : 'none'
        }}
        transition={{ duration: 0.4, ease: luxuryEasing as any }}
      >
        <div className="max-w-[1800px] mx-auto px-8 lg:px-12 py-8 flex justify-between items-center">
          <motion.button 
            onClick={() => navigate('/')}
            className="text-[#F5F5F3] font-serif text-2xl tracking-tight"
            whileHover={{ opacity: 0.6 }}
            transition={{ duration: 0.4 }}
          >
            Cleub Automation
          </motion.button>
          <div className="hidden md:flex items-center gap-16">
            {[
              { label: 'Home', href: '/' },
              { label: 'About Us', href: '/about' },
            ].map((link) => (
              <motion.button
                key={link.label}
                onClick={() => navigate(link.href)}
                className="text-[#F5F5F3] text-[10px] tracking-[0.35em] uppercase hover:opacity-50 transition-opacity duration-500"
                whileHover={{ y: -2 }}
                transition={{ duration: 0.3 }}
              >
                {link.label}
              </motion.button>
            ))}
            {user ? (
              <motion.div whileHover={{ y: -2 }} transition={{ duration: 0.3 }}>
                <ProfileMenu />
              </motion.div>
            ) : (
              <motion.button
                onClick={() => navigate('/login')}
                className="text-[#F5F5F3] text-[10px] tracking-[0.35em] uppercase hover:opacity-50 transition-opacity duration-500"
                whileHover={{ y: -2 }}
                transition={{ duration: 0.3 }}
              >
                Sign In
              </motion.button>
            )}
          </div>
        </div>
      </motion.nav>

      <main>
        {/* ============================================ */}
        {/* HERO SECTION */}
        {/* ============================================ */}
        <section className="min-h-screen flex items-center pt-32 pb-16">
          <div className="max-w-[1800px] mx-auto px-8 lg:px-16 w-full">
            <motion.div
              className="max-w-[95%] lg:max-w-[85%]"
              variants={staggerContainer}
              initial="hidden"
              animate="visible"
            >
              <motion.div className="flex items-center gap-3 mb-8" variants={fadeInUp}>
                <Scale className="w-5 h-5 text-[#F5F5F3]/40" />
                <p className="text-[#F5F5F3]/40 text-[10px] tracking-[0.4em] uppercase">
                  Terms & Conditions
                </p>
              </motion.div>

              <div className="overflow-hidden mb-4">
                <motion.h1 
                  className="font-serif text-[clamp(2.5rem,7vw,7rem)] leading-[0.95] text-[#F5F5F3] tracking-tight"
                  variants={textReveal}
                >
                  Standard of Engagement.
                </motion.h1>
              </div>

              <motion.p 
                className="text-[#F5F5F3]/60 text-sm tracking-[0.3em] uppercase mt-8"
                variants={fadeInUp}
              >
                Effective Date: 12/2/2025
              </motion.p>

              <motion.p 
                className="text-[#F5F5F3]/70 text-base lg:text-lg leading-relaxed max-w-[800px] mt-8"
                variants={fadeInUp}
              >
                This document establishes the formal Standard of Engagement between you and Cleub Automation. By accessing or utilizing our digital properties and advisory services, you confirm your unconditional acceptance of these Terms and Conditions.
              </motion.p>
            </motion.div>
          </div>
        </section>

        {/* ============================================ */}
        {/* TERMS SECTIONS */}
        {/* ============================================ */}
        {sections.map((section, idx) => (
          <AnimatedSection 
            key={section.number} 
            className="py-32" 
            dark={section.number % 2 === 1}
          >
            <div className="max-w-[1800px] mx-auto px-8 lg:px-16">
              <motion.div className="max-w-[85%] lg:max-w-[75%]" variants={staggerContainer}>
                
                {/* Section Header */}
                <motion.div className="mb-16" variants={fadeInUp}>
                  <p className={`text-[9px] tracking-[0.4em] uppercase mb-6 ${
                    section.number % 2 === 1 
                      ? 'text-[#F5F5F3]/40' 
                      : 'text-[#6B6B6B]/60'
                  }`}>
                    Section {section.number}
                  </p>
                  
                  <div className="overflow-hidden mb-4">
                    <motion.h2 
                      className={`font-serif text-[clamp(1.8rem,4vw,3rem)] leading-[0.95] tracking-tight ${
                        section.number % 2 === 1 
                          ? 'text-[#F5F5F3]' 
                          : 'text-[#0A0A0A]'
                      }`}
                      variants={textReveal}
                    >
                      {section.title}
                    </motion.h2>
                  </div>
                  
                  {section.subtitle && (
                    <motion.p 
                      className={`text-sm tracking-[0.2em] ${
                        section.number % 2 === 1 
                          ? 'text-[#F5F5F3]/50' 
                          : 'text-[#6B6B6B]/50'
                      }`}
                      variants={fadeInUp}
                    >
                      {section.subtitle}
                    </motion.p>
                  )}
                </motion.div>

                {/* Content or Items */}
                {section.content && (
                  <motion.p 
                    className={`text-base leading-relaxed mb-8 ${
                      section.number % 2 === 1 
                        ? 'text-[#F5F5F3]/70' 
                        : 'text-[#6B6B6B]/70'
                    }`}
                    variants={fadeInUp}
                  >
                    {section.content}
                  </motion.p>
                )}

                {section.items && (
                  <motion.div className="space-y-4" variants={staggerContainer}>
                    {section.items.map((item, itemIdx) => (
                      <motion.div
                        key={itemIdx}
                        className={`p-6 border transition-all duration-500 ${
                          section.number % 2 === 1
                            ? 'bg-[#0A0A0A] border-[#1A1A1A] group hover:border-[#F5F5F3]/20'
                            : 'bg-white border-[#E5E5E5] group hover:bg-[#0A0A0A] hover:text-[#F5F5F3] hover:border-[#1A1A1A]'
                        }`}
                        variants={fadeInUp}
                      >
                        <h3 className={`font-serif text-lg mb-2 transition-colors duration-700 ${
                          section.number % 2 === 1
                            ? 'text-[#F5F5F3]'
                            : 'text-[#0A0A0A] group-hover:text-[#F5F5F3]'
                        }`}>
                          {item.label}
                        </h3>
                        <p className={`text-sm leading-relaxed transition-colors duration-700 ${
                          section.number % 2 === 1
                            ? 'text-[#F5F5F3]/60'
                            : 'text-[#6B6B6B] group-hover:text-[#F5F5F3]/70'
                        }`}>
                          {item.desc}
                        </p>
                      </motion.div>
                    ))}
                  </motion.div>
                )}
              </motion.div>
            </div>
          </AnimatedSection>
        ))}

        {/* ============================================ */}
        {/* CONTACT SECTION */}
        {/* ============================================ */}
        <AnimatedSection className="py-40" dark={false}>
          <div className="max-w-[1800px] mx-auto px-8 lg:px-16">
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-16 lg:gap-24 items-center">
              {/* Left - Heading */}
              <motion.div variants={staggerContainer}>
                <motion.p 
                  className="text-[9px] tracking-[0.4em] uppercase text-[#6B6B6B]/60 mb-8"
                  variants={fadeInUp}
                >
                  Office of Engagement
                </motion.p>

                <div className="overflow-hidden mb-12">
                  <motion.h2 
                    className="font-serif text-[clamp(2rem,5vw,4rem)] leading-[0.95] text-[#0A0A0A] tracking-tight"
                    variants={textReveal}
                  >
                    Formal Inquiries.
                  </motion.h2>
                </div>

                <motion.p 
                  className="text-[#6B6B6B] text-base leading-relaxed max-w-[600px]"
                  variants={fadeInUp}
                >
                  For questions regarding these Terms or our Services, reach out directly to our engagement office.
                </motion.p>
              </motion.div>

              {/* Right - Contact Info */}
              <motion.div className="space-y-6" variants={staggerContainer}>
                <motion.a 
                  href="mailto:support@cleub.com"
                  className="block group"
                  variants={fadeInUp}
                >
                  <div className="flex items-center gap-4 p-6 bg-white border border-[#E5E5E5] group-hover:bg-[#0A0A0A] group-hover:text-[#F5F5F3] transition-all duration-700">
                    <Mail className="w-5 h-5 text-[#6B6B6B] group-hover:text-[#F5F5F3] transition-colors duration-700" />
                    <div className="flex-1">
                      <p className="text-[9px] tracking-[0.35em] uppercase text-[#6B6B6B] group-hover:text-[#F5F5F3]/40 transition-colors duration-700 mb-1">Email</p>
                      <p className="font-serif text-lg text-[#0A0A0A] group-hover:text-[#F5F5F3] transition-colors duration-700">support@cleub.com</p>
                    </div>
                  </div>
                </motion.a>

                <motion.a 
                  href="tel:+919667603999"
                  className="block group"
                  variants={fadeInUp}
                >
                  <div className="flex items-center gap-4 p-6 bg-white border border-[#E5E5E5] group-hover:bg-[#0A0A0A] group-hover:text-[#F5F5F3] transition-all duration-700">
                    <Phone className="w-5 h-5 text-[#6B6B6B] group-hover:text-[#F5F5F3] transition-colors duration-700" />
                    <div className="flex-1">
                      <p className="text-[9px] tracking-[0.35em] uppercase text-[#6B6B6B] group-hover:text-[#F5F5F3]/40 transition-colors duration-700 mb-1">Direct Line</p>
                      <p className="font-serif text-lg text-[#0A0A0A] group-hover:text-[#F5F5F3] transition-colors duration-700">+91 9667603999</p>
                    </div>
                  </div>
                </motion.a>
              </motion.div>
            </div>
          </div>
        </AnimatedSection>

        {/* ============================================ */}
        {/* FOOTER CTA */}
        {/* ============================================ */}
        <AnimatedSection className="py-20" dark={true}>
          <div className="max-w-[1800px] mx-auto px-8 lg:px-16">
            <div className="flex flex-col sm:flex-row items-center justify-between gap-8">
              <motion.button
                onClick={() => {
                  navigate('/');
                  setTimeout(() => window.scrollTo(0, 0), 50);
                }}
                className="text-[#F5F5F3] text-[10px] tracking-[0.35em] uppercase hover:opacity-50 transition-opacity duration-500"
                variants={fadeInUp}
              >
                Back to Home
              </motion.button>
              <motion.p 
                className="text-[9px] tracking-[0.35em] text-[#F5F5F3]/30"
                variants={fadeInUp}
              >
                © 2025 Cleub Automation. The standard in system certainty.
              </motion.p>
            </div>
          </div>
        </AnimatedSection>
      </main>
    </div>
  );
};

export default TermsAndConditions;
