import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { useNavigate } from 'react-router-dom';
import SiteNav from '@/components/ui/site-nav';

const TermsAndConditions = () => {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-950 via-slate-900 to-black">
      <SiteNav
        brand="Cleub Automation"
        links={[
          { label: 'Home', href: '/' },
          { label: 'About Us', href: '/about' },
        ]}
      />

      <main className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="text-center mb-12">
          <h1 className="text-4xl sm:text-5xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-slate-100 via-white to-slate-300 mb-4">
            Terms and Conditions
          </h1>
          <p className="text-slate-400">Last Updated: {new Date().toLocaleDateString()}</p>
        </div>

        <Card className="bg-slate-900/70 backdrop-blur-sm border border-slate-800 mb-8">
          <CardContent className="p-8 space-y-6 text-slate-300">
            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">Agreement to Terms</h2>
              <p className="leading-relaxed">
                By accessing or using Cleub Automation's website, services, or planning platform, you agree to be bound by these Terms and Conditions. If you do not agree to these terms, please do not use our services.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">Services Description</h2>
              <p className="leading-relaxed mb-3">
                Cleub Automation provides premium home automation solutions, including:
              </p>
              <ul className="list-disc list-inside space-y-2 leading-relaxed">
                <li>Online project planning and cost estimation tools</li>
                <li>Home automation system design and installation</li>
                <li>Home theater and professional studio setup</li>
                <li>Consultation and advisory services</li>
                <li>Supply of automation products and components</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">User Account and Responsibilities</h2>
              <div className="space-y-3">
                <p className="leading-relaxed">
                  To access certain features, you may need to create an account. You are responsible for:
                </p>
                <ul className="list-disc list-inside space-y-2 leading-relaxed ml-4">
                  <li>Maintaining the confidentiality of your account credentials</li>
                  <li>All activities that occur under your account</li>
                  <li>Providing accurate, current, and complete information</li>
                  <li>Notifying us immediately of any unauthorized use</li>
                </ul>
                <p className="leading-relaxed">
                  We reserve the right to suspend or terminate accounts that violate these terms.
                </p>
              </div>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">Cost Estimates and Proposals</h2>
              <p className="leading-relaxed">
                The cost estimates generated by our planning platform are approximate and for informational purposes only. Final project costs may vary based on:
              </p>
              <ul className="list-disc list-inside space-y-2 leading-relaxed mt-3">
                <li>Site inspection findings and technical requirements</li>
                <li>Product availability and pricing fluctuations</li>
                <li>Customization needs and scope changes</li>
                <li>Installation complexity and site conditions</li>
                <li>Additional services or components identified during consultation</li>
              </ul>
              <p className="leading-relaxed mt-3">
                All formal quotations and contracts will be provided separately and supersede any estimates from our planning tool.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">Intellectual Property</h2>
              <p className="leading-relaxed">
                All content, features, and functionality of our website and services, including but not limited to text, graphics, logos, software, and designs, are owned by Cleub Automation and protected by intellectual property laws. You may not:
              </p>
              <ul className="list-disc list-inside space-y-2 leading-relaxed mt-3">
                <li>Copy, modify, or distribute our proprietary content without permission</li>
                <li>Reverse engineer or extract source code from our platform</li>
                <li>Use our trademarks or branding without authorization</li>
                <li>Create derivative works based on our services</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">Project Inquiries and Consultations</h2>
              <p className="leading-relaxed">
                When you submit an inquiry or request a consultation:
              </p>
              <ul className="list-disc list-inside space-y-2 leading-relaxed mt-3">
                <li>We will respond within 24-48 business hours</li>
                <li>Consultations may be conducted virtually or on-site based on project scope</li>
                <li>Detailed proposals and contracts will be provided for approved projects</li>
                <li>You are not obligated to proceed with any service until a formal contract is signed</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">Service Agreements and Installation</h2>
              <p className="leading-relaxed">
                For installation projects, separate service agreements will outline:
              </p>
              <ul className="list-disc list-inside space-y-2 leading-relaxed mt-3">
                <li>Detailed scope of work and deliverables</li>
                <li>Project timelines and milestones</li>
                <li>Payment terms and schedules</li>
                <li>Warranty coverage and support terms</li>
                <li>Change order procedures</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">Limitation of Liability</h2>
              <p className="leading-relaxed">
                To the fullest extent permitted by law, Cleub Automation shall not be liable for:
              </p>
              <ul className="list-disc list-inside space-y-2 leading-relaxed mt-3">
                <li>Indirect, incidental, or consequential damages</li>
                <li>Loss of profits, data, or business opportunities</li>
                <li>Damages arising from reliance on cost estimates without formal quotation</li>
                <li>Third-party product defects or service interruptions</li>
                <li>Force majeure events beyond our reasonable control</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">Warranties and Disclaimers</h2>
              <p className="leading-relaxed">
                Our services are provided "as is" without warranties of any kind, express or implied. While we strive for excellence, we do not guarantee:
              </p>
              <ul className="list-disc list-inside space-y-2 leading-relaxed mt-3">
                <li>Uninterrupted or error-free operation of our website</li>
                <li>Accuracy or completeness of planning tool results</li>
                <li>Compatibility with all third-party devices and systems</li>
              </ul>
              <p className="leading-relaxed mt-3">
                Installed equipment and systems are subject to manufacturer warranties, which will be detailed in service agreements.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">Privacy and Data Protection</h2>
              <p className="leading-relaxed">
                Your use of our services is also governed by our Privacy Policy. We are committed to protecting your personal information and complying with applicable data protection laws. Please review our Privacy Policy for details on data collection and usage.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">Prohibited Uses</h2>
              <p className="leading-relaxed mb-3">You agree not to:</p>
              <ul className="list-disc list-inside space-y-2 leading-relaxed">
                <li>Use our services for any unlawful purpose or in violation of these terms</li>
                <li>Attempt to gain unauthorized access to our systems or networks</li>
                <li>Interfere with or disrupt the operation of our services</li>
                <li>Transmit viruses, malware, or harmful code</li>
                <li>Impersonate any person or entity</li>
                <li>Harvest or collect user information without consent</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">Modifications to Terms</h2>
              <p className="leading-relaxed">
                We reserve the right to modify these Terms and Conditions at any time. Changes will be effective immediately upon posting on our website. Your continued use of our services after modifications constitutes acceptance of the updated terms.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">Termination</h2>
              <p className="leading-relaxed">
                We may terminate or suspend your access to our services immediately, without prior notice, for any breach of these Terms and Conditions. Upon termination, your right to use our services will cease immediately.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">Governing Law and Dispute Resolution</h2>
              <p className="leading-relaxed">
                These Terms and Conditions are governed by the laws of India. Any disputes arising from these terms or our services shall be resolved through:
              </p>
              <ul className="list-disc list-inside space-y-2 leading-relaxed mt-3">
                <li>Good faith negotiation between parties</li>
                <li>Mediation if negotiation fails</li>
                <li>Arbitration in accordance with Indian arbitration laws</li>
                <li>Courts in Delhi, India, if arbitration is not applicable</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">Severability</h2>
              <p className="leading-relaxed">
                If any provision of these Terms and Conditions is found to be unenforceable or invalid, that provision will be limited or eliminated to the minimum extent necessary, and the remaining provisions will remain in full force and effect.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">Contact Information</h2>
              <p className="leading-relaxed">
                For questions about these Terms and Conditions or our services, please contact us at:
              </p>
              <div className="mt-3 space-y-1">
                <p>Email: <a href="mailto:support@cleub.com" className="text-teal-400 hover:underline">support@cleub.com</a></p>
                <p>Phone: <a href="tel:+919667603999" className="text-teal-400 hover:underline">+91 9667603999</a></p>
              </div>
            </section>
          </CardContent>
        </Card>

        <div className="text-center">
          <Button onClick={() => navigate('/')} variant="outline" className="border-teal-600 text-teal-400 hover:bg-teal-600/10">
            Back to Home
          </Button>
        </div>
      </main>

      <footer className="border-t border-white/10 bg-black/20 backdrop-blur-xl py-6 mt-12">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center text-sm text-slate-400">
          &copy; {new Date().getFullYear()} Cleub Automation. All rights reserved.
        </div>
      </footer>
    </div>
  );
};

export default TermsAndConditions;
